version: '3'
services:
  app:
    container_name: movies-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./movies:/var/www/html
    command: bash -c "php artisan scribe:generate && php artisan serve --host=0.0.0.0 --port=8000"